"""Type stubs for fasthtml.common module."""
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

def fast_app(with_session: bool = False, secret_key: str = "") -> Tuple[Any, Any]: ...

class Link:
    def __init__(self, rel: str = "", href: str = "", **kwargs: Any) -> None: ...

class Title:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class Main:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Div:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class H1:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class H3:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class H4:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class P:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class Form:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Label:
    def __init__(self, *args: Any, for_: str = "", **kwargs: Any) -> None: ...

class Input:
    def __init__(self, type: str = "", name: str = "", value: str = "", checked: bool = False, **kwargs: Any) -> None: ...

class Span:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class Textarea:
    def __init__(self, id: str = "", name: str = "", placeholder: str = "", rows: str = "", **kwargs: Any) -> None: ...

class Button:
    def __init__(self, content: Any = "", type: str = "", **kwargs: Any) -> None: ...

class A:
    def __init__(self, content: Any = "", href: str = "", **kwargs: Any) -> None: ...