"""Type stubs for fasthtml.components module."""
from typing import Any, List, Optional, Union

class Group:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Div:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class H3:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class P:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class Script:
    def __init__(self, content: Any = "", src: str = "", **kwargs: Any) -> None: ...

class Pre:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class Label:
    def __init__(self, *args: Any, for_: str = "", **kwargs: Any) -> None: ...

class Input:
    def __init__(self, type: str = "", name: str = "", value: str = "", checked: bool = False, **kwargs: Any) -> None: ...

class Span:
    def __init__(self, content: Any = "", **kwargs: Any) -> None: ...

class Textarea:
    def __init__(self, id: str = "", name: str = "", placeholder: str = "", rows: str = "", **kwargs: Any) -> None: ...